### ISSUE TITLE
Failed segmenetation on side faces and far images

### ISSUE THREAD

**Issue by achalshah20** [YuvalNirkin/face_segmentation#8]
Hi, Thanks for this project. It works good for the front faces. However, for some scenarios results are not so good.

- if person in the image is far from camera(no segmentation at all)
- Side faces (bad segmentation)

Few suggestions or update to this paper will be great help. Thanks!

**Comment by YuvalNirkin** [comment]
We treat detection and segmentation as separate problems, the segmentation must be follow a detection step. In order to not impose a specific detection implementation, this segmentation assumes an already cropped image around the head.

For best results crop your images using this function (which was also used for training the network):
[https://github.com/YuvalNirkin/find_face_landmarks/blob/16cd2443d903518a8dfe417a953851e5ccc47a80/sequence_face_landmarks/utilities.cpp#L291-L344](https://github.com/YuvalNirkin/find_face_landmarks/blob/16cd2443d903518a8dfe417a953851e5ccc47a80/sequence_face_landmarks/utilities.cpp#L291-L344).

For a complete image preprocessing example:
[https://github.com/YuvalNirkin/face_swap/blob/64c7eebbb981d87eac851d854e69934451a2f9ff/face_swap/face_swap.cpp#L310-L340](https://github.com/YuvalNirkin/face_swap/blob/64c7eebbb981d87eac851d854e69934451a2f9ff/face_swap/face_swap.cpp#L310-L340)

**Comment by achalshah20** [comment]
Hi @YuvalNirkin Yes. So I did detection using another model followed by your segmentation model. It works reasonably well with front faces. But it doesn't work with side faces.  Is this model trained for side faces as well? Thanks!

**Comment by Rettichhuang** [comment]
Hi,thanks for your project.i am wondering that if u can provide face segment dataset including photos and labels.its a little difficult to make a train-dataset myself.Thanks~!

**Comment by YuvalNirkin** [comment]
@Rettichhuang 
Hey, please see #6.

**Comment by ileniTudor** [comment]
> Hi,thanks for your project.i am wondering that if u can provide face segment dataset including photos and labels.its a little difficult to make a train-dataset myself.Thanks~!

Can take a look on this dataset:
http://www.cs.ubbcluj.ro/~dadi/face-hair-segm-database.html
